---
version: "3"

tasks:
  install:
    cmds:
      - "brew install markdownlint-cli yamllint golangci-lint go go-task"

  lint:
    cmds:
      - "markdownlint ."
      - "yamllint ."
      - "golangci-lint run"

  test:
    cmds:
      - "go test ."
...
